import React, { useState, useRef, useEffect } from "react";
import { AnimationOnScroll } from "react-animation-on-scroll";

const Test = () => {
  return (
    <div className={""}>
      <video
        style={{ position: "fixed" }}
        className="object-cover w-full h-full"
        src="video/faq.mov"
        playsInline
        autoPlay
        muted
        loop
      ></video>
      <div className="w-full h-full overflow-scroll scrollbar-hide" style={{ position: "fixed" }}>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
        <h1>
          djsdkahsjxhassssssssssssssssssssssssssssssssssssssssssssssssssssss
        </h1>
      </div>
    </div>
  );
};

export default Test;
